<?php

namespace DoctrineORMModule\Proxy\__CG__\Produto\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProdutoTenis extends \Produto\Entity\ProdutoTenis implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'sugestaoCoresProdutos', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'perspectiva', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'tecnologias', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'idtenis', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'titulo', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'slug', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'src', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'nossoNumero', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'numeracaoInicial', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'numeracaoFinal', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'subcategoriaTenis', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'descricao');
        }

        return array('__isInitialized__', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'sugestaoCoresProdutos', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'perspectiva', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'tecnologias', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'idtenis', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'titulo', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'slug', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'src', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'nossoNumero', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'numeracaoInicial', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'numeracaoFinal', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'subcategoriaTenis', '' . "\0" . 'Produto\\Entity\\ProdutoTenis' . "\0" . 'descricao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProdutoTenis $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdtenis()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdtenis();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtenis', array());

        return parent::getIdtenis();
    }

    /**
     * {@inheritDoc}
     */
    public function getSrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSrc', array());

        return parent::getSrc();
    }

    /**
     * {@inheritDoc}
     */
    public function getNossoNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNossoNumero', array());

        return parent::getNossoNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeracaoInicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeracaoInicial', array());

        return parent::getNumeracaoInicial();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeracaoFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeracaoFinal', array());

        return parent::getNumeracaoFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtenis($idtenis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtenis', array($idtenis));

        return parent::setIdtenis($idtenis);
    }

    /**
     * {@inheritDoc}
     */
    public function setSrc($src)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSrc', array($src));

        return parent::setSrc($src);
    }

    /**
     * {@inheritDoc}
     */
    public function setNossoNumero($nossoNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNossoNumero', array($nossoNumero));

        return parent::setNossoNumero($nossoNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeracaoInicial($numeracaoInicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeracaoInicial', array($numeracaoInicial));

        return parent::setNumeracaoInicial($numeracaoInicial);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeracaoFinal($numeracaoFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeracaoFinal', array($numeracaoFinal));

        return parent::setNumeracaoFinal($numeracaoFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubcategoriaTenis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubcategoriaTenis', array());

        return parent::getSubcategoriaTenis();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubcategoriaTenis($subcategoriaTenis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubcategoriaTenis', array($subcategoriaTenis));

        return parent::setSubcategoriaTenis($subcategoriaTenis);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseTecnologia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseTecnologia', array());

        return parent::getBaseTecnologia();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseTecnologia($baseTecnologia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseTecnologia', array($baseTecnologia));

        return parent::setBaseTecnologia($baseTecnologia);
    }

    /**
     * {@inheritDoc}
     */
    public function getSugestaoCoresProdutos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSugestaoCoresProdutos', array());

        return parent::getSugestaoCoresProdutos();
    }

    /**
     * {@inheritDoc}
     */
    public function getPerspectiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerspectiva', array());

        return parent::getPerspectiva();
    }

    /**
     * {@inheritDoc}
     */
    public function setSugestaoCoresProdutos($sugestaoCoresProdutos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSugestaoCoresProdutos', array($sugestaoCoresProdutos));

        return parent::setSugestaoCoresProdutos($sugestaoCoresProdutos);
    }

    /**
     * {@inheritDoc}
     */
    public function setPerspectiva($perspectiva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerspectiva', array($perspectiva));

        return parent::setPerspectiva($perspectiva);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getTecnologias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTecnologias', array());

        return parent::getTecnologias();
    }

    /**
     * {@inheritDoc}
     */
    public function setTecnologias($tecnologias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTecnologias', array($tecnologias));

        return parent::setTecnologias($tecnologias);
    }

}
