<div id="popup-login">
	<span>
	 <img src="<?=$this->basepath("img/load.gif")?>">
	 <p>Carregando Aguarde...</p>
	</span>
</div>


<div id="adm-popup">
	<p>
		<h4></h4>
		<conteudo class="conteudo">dsa</conteudo>
	</p>
</div>
	<a href="" title="Gerenciamento de Banners:" class="openPopup" rel="banner"><img src="<?=$this->basepath("img/btn_banner.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciamento de Mídia:" class="openPopup" rel="midia"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciamento de Onde Comprar:" class="openPopup" rel="ondeComprar"><img src="<?=$this->basepath("img/btn_onde-comprarr.png")?>" class="img-polaroid" width="300"></a>
    <a href="" title="Gerenciamento de Produtos:" class="openPopup" rel="produtos"><img src="<?=$this->basepath("img/btn_produtos.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciamento de Tecnologia:" class="openPopup" rel="tecnologiaAdm"><img src="<?=$this->basepath("img/btn_tecnologia.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciamento de Clipping:" class="openPopup" rel="wallpaper"><img src="<?=$this->basepath("img/clipping.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciar Newsletter:" class="openPopup" rel="newslatter"><img src="<?=$this->basepath("img/news.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciar Fale Conosco:" class="openPopup" rel="faleconosco"><img src="<?=$this->basepath("img/btn_contato.png")?>" class="img-polaroid" width="300"></a>
    